name = "edge1223545"
main = "_worker.js"
compatibility_date = "2025-05-15"

[[routes]]
pattern = "edge1.c1cada.ccwu.cc"
zone_name = "c1cada.ccwu.cc"

[observability.logs]
enabled = true

[[kv_namespaces]]
binding = "KV"
id = "3eade0fd9c5941249a2c8a44563824d6"

[vars]
ADMIN = "BBh@20050305"
