# wrangler.toml
name = 'edgetunnel'

main = "_worker.js"
compatibility_date = "2025-11-04"
keep_vars = true

# ...
[vars]
ADMIN = "BBh@20050305"
# ...

# ...
[[kv_namespaces]]
binding = "KV"
id = "3eade0fd9c5941249a2c8a44563824d6"
# ...


#[[kv_namespaces]]
#binding = "KV"			#KV绑定名默认不可修改
#id = ""				#KV数据库id
